server:
    port: 8085
target-service-uri: ${TARGET_SERVICE_URI:http://httpbin.org:80}
logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      reactor.netty.http.client: DEBUG
      org.springframework.security: DEBUG
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/auth/realms/core}
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:access-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:7gKVZjLweVxIg1fe22x1xQUdyd0AT6OW}
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_URI:http://localhost:8090/auth/realms/core/protocol/openid-connect/certs}
opa:
  data:
    rest-endpoint: ${OPA_DATA_REST_ENDPOINT:http://localhost:8181/v1/data/rest/allow}
